services:
  everypay_mock:
    build: .
    container_name: everypay_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./banking:/app/banking
      - ./oauth:/app/oauth
      - ./config:/app/config
      - ./manage.py:/app/manage.py
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOW_ALL_ORIGINS: ${CORS_ALLOW_ALL_ORIGINS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - everypay_network

  db:
    image: postgres:16-alpine
    container_name: everypay_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - everypay_network

networks:
  everypay_network:
    driver: bridge

volumes:
  postgres_data:
