# Generated by Django 6.0.5 on 2026-06-11 08:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "inn",
                    models.CharField(
                        help_text="Состоит из 12 цифр",
                        max_length=12,
                        unique=True,
                        verbose_name="ИНН компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="ThirdParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Bank", "Банк"), ("Service", "Сервис")],
                        max_length=10,
                        verbose_name="Тип сервиса",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Например, sber, tbank",
                        max_length=20,
                        unique=True,
                        verbose_name="Код сервиса",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название сервиса"),
                ),
                ("description", models.TextField(max_length=512)),
            ],
            options={
                "verbose_name": "Внешний сервис",
                "verbose_name_plural": "Внешние сервисы",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB",
                        help_text="Код валюты по ISO 4217 (RUB, USD, EUR)",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Business", "Юридическое лицо"),
                            ("Personal", "Физическое лицо"),
                        ],
                        help_text="Физ/Юр лица",
                        max_length=20,
                        verbose_name="Тип счета",
                    ),
                ),
                (
                    "account_sub_type",
                    models.CharField(
                        choices=[
                            ("CurrentAccount", "Расчётный"),
                            ("Savings", "Сберегательный"),
                            ("Loan", "Кредитный"),
                        ],
                        max_length=30,
                        verbose_name="Подтип счета",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Enabled", "Активен"),
                            ("Disabled", "Закрыт"),
                            ("Deleted", "Удалён"),
                        ],
                        default="Enabled",
                        max_length=20,
                    ),
                ),
                (
                    "bban",
                    models.CharField(
                        blank=True,
                        help_text="Расчетный счет, обычно 20 цифр",
                        max_length=34,
                        verbose_name="Номер счёта (Basic Bank Account Number)",
                    ),
                ),
                ("status_update_datetime", models.DateTimeField(auto_now=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="banking.company",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="banking.thirdparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счёт",
                "verbose_name_plural": "Счета",
            },
        ),
        migrations.CreateModel(
            name="StatementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_booking_date_time", models.DateTimeField()),
                ("to_booking_date_time", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_requests",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выписка",
                "verbose_name_plural": "Выписки",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "credit_debit_indicator",
                    models.CharField(
                        choices=[("Credit", "Приход"), ("Debit", "Расход")],
                        max_length=6,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Booked", "Проведена"), ("Pending", "Ожидает")],
                        default="Booked",
                        max_length=10,
                    ),
                ),
                (
                    "booking_date_time",
                    models.DateTimeField(verbose_name="Дата транзакции"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        verbose_name="Сумма транзакции",
                    ),
                ),
                (
                    "value_date_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата, когда деньги становятся доступны",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Назначение платежа",
                    ),
                ),
                (
                    "debtor_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Название плательщика",
                    ),
                ),
                (
                    "debtor_account",
                    models.CharField(
                        blank=True,
                        max_length=34,
                        verbose_name="Номер счета плательщика",
                    ),
                ),
                (
                    "creditor_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Название получателя",
                    ),
                ),
                (
                    "creditor_account",
                    models.CharField(
                        blank=True,
                        max_length=34,
                        verbose_name="Номер счета получателя",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB",
                        help_text="Код валюты по ISO 4217 (RUB, USD, EUR)",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Обычно 6 цифр (может быть другой банковский документ)",
                        max_length=6,
                        verbose_name="Номер платежного поручения",
                    ),
                ),
                (
                    "debtor_bic",
                    models.CharField(
                        blank=True,
                        help_text="Обычно 11 цифр",
                        max_length=11,
                        verbose_name="БИК плательщика",
                    ),
                ),
                (
                    "creditor_bic",
                    models.CharField(
                        blank=True,
                        help_text="Обычно 11 цифр",
                        max_length=11,
                        verbose_name="БИК получателя",
                    ),
                ),
                (
                    "tax_uip",
                    models.CharField(
                        blank=True,
                        help_text="Уникален в пределах одного платежа. "
                        "Обычно 22 символа. используется для платежей в бюджет",
                        max_length=25,
                        verbose_name="Уникальный идентификатор платежа",
                    ),
                ),
                (
                    "tax_kbk",
                    models.CharField(
                        blank=True,
                        help_text="Обычно 20 цифр. Определяет вид налога",
                        max_length=20,
                        verbose_name="Код бюджетной классификации",
                    ),
                ),
                (
                    "tax_oktmo",
                    models.CharField(
                        blank=True,
                        help_text="Муниципальное образование, куда идет платеж",
                        max_length=11,
                        verbose_name="Код территории по ОКТМО",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["-booking_date_time"],
            },
        ),
    ]
